/**
 * External dependencies
 */
import { omit } from 'lodash'
import { i18n } from 'stackable'

/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n'
import { addFilter } from '@wordpress/hooks'

// Remove text from block designs being applied.
addFilter( 'stackable.image-box.design.no-text-attributes', 'stackable/image-box', attributes => {
	return omit( attributes, [
		'subtitle1',
		'subtitle2',
		'subtitle3',
		'subtitle4',
		'title1',
		'title2',
		'title3',
		'title4',
		'description1',
		'description2',
		'description3',
		'description4',
	] )
} )

// Ignore these attributes when exporting / applying designs.
addFilter( 'stackable.image-box.design.filtered-block-attributes', 'stackable/image-box', ( attributes, blockAttributes = null ) => {
	return omit( attributes, [
		'link1Url',
		'link2Url',
		'link3Url',
		'link4Url',
		'link1NewTab',
		'link2NewTab',
		'link3NewTab',
		'link4NewTab',
		'link1NoFollow',
		'link2NoFollow',
		'link3NoFollow',
		'link4NoFollow',
		'image1Id',
		...( blockAttributes && blockAttributes.image1Id ? [ 'image1Url' ] : [] ),
		'image2Id',
		...( blockAttributes && blockAttributes.image2Id ? [ 'image2Url' ] : [] ),
		'image3Id',
		...( blockAttributes && blockAttributes.image3Id ? [ 'image3Url' ] : [] ),
		'image4Id',
		...( blockAttributes && blockAttributes.image4Id ? [ 'image4Url' ] : [] ),
	] )
} )

addFilter( 'stackable.image-box.edit.designs', 'stackable/image-box', designs => {
	return {
		...designs,
		corporateLight1: {
			label: __( 'Corporate Light 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-image-box-design-corporate-light-01.jpg',
			attributes: {
				design: 'plain',
				columns: 2,
				borderRadius: 0,
				image1FullWidth: 1200,
				image1FullHeight: 800,
				image2FullWidth: 1200,
				image2FullHeight: 800,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-light-01-01.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-light-01-02.jpg',
				showOverlay: true,
				overlayBackgroundColor: '#ffffff',
				overlayOpacity: 0.1,
				overlayHoverBackgroundColor: '#ffb20b',
				overlayHoverOpacity: 0.8,
				imageHoverEffect: 'zoom-in',
				showSubtitle: false,
				subtitleFontFamily: 'Roboto Condensed',
				subtitleFontWeight: '400',
				subtitleLetterSpacing: 0.5,
				subtitleColor: '#ffffff',
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleColor: '#ffffff',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				arrowColor: '#728a23',
				paddingTop: 130,
				paddingBottom: 130,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#ffffff',
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#ffb20b',
				blockDescriptionBottomMargin: 50,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#707070',
			},
		},
		corporateLight2: {
			label: __( 'Corporate Light 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-image-box-design-corporate-light-02.jpg',
			attributes: {
				design: 'plain',
				columns: 2,
				borderRadius: 0,
				image1FullWidth: 1200,
				image1FullHeight: 800,
				image2FullWidth: 1200,
				image2FullHeight: 800,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-light-02-02.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-dark-01-01.jpg',
				showOverlay: true,
				overlayBackgroundColor: '#c49732',
				overlayOpacity: 0.2,
				overlayHoverBackgroundColor: '#1e55d3',
				overlayHoverOpacity: 0.8,
				imageHoverEffect: 'zoom-in',
				showSubtitle: false,
				subtitleFontFamily: 'Roboto Condensed',
				subtitleFontWeight: '400',
				subtitleLetterSpacing: 0.5,
				subtitleColor: '#ffffff',
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleColor: '#c49732',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				arrowColor: '#728a23',
				paddingTop: 130,
				paddingBottom: 130,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#ffffff',
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#6a91eb',
				blockDescriptionBottomMargin: 50,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#707070',
			},
		},
		corporateDark1: {
			label: __( 'Corporate Dark 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-image-box-design-corporate-dark-01.jpg',
			attributes: {
				design: 'plain',
				columns: 2,
				borderRadius: 0,
				image1FullWidth: 1200,
				image1FullHeight: 800,
				image2FullWidth: 2250,
				image2FullHeight: 1500,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-dark-01-02.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-dark-01-01.jpg',
				showOverlay: true,
				overlayBackgroundColor: '#ffffff',
				overlayOpacity: 0.3,
				overlayHoverBackgroundColor: '#c5dfb4',
				overlayHoverOpacity: 0.8,
				imageHoverEffect: 'zoom-in',
				showSubtitle: false,
				subtitleFontFamily: 'Roboto Condensed',
				subtitleFontWeight: '400',
				subtitleLetterSpacing: 0.5,
				subtitleColor: '#728a23',
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleColor: '#062a65',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#707070',
				arrowColor: '#728a23',
				paddingTop: 130,
				paddingBottom: 130,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#081831',
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#eeffb5',
				blockDescriptionBottomMargin: 50,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
			},
		},
		corporateDark2: {
			label: __( 'Corporate Dark 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-image-box-design-corporate-dark-02.jpg',
			attributes: {
				design: 'plain',
				columns: 2,
				borderRadius: 0,
				image1FullWidth: 1200,
				image1FullHeight: 800,
				image2FullWidth: 1200,
				image2FullHeight: 800,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-dark-02-01.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-dark-02-02.jpg',
				showOverlay: true,
				overlayBackgroundColor: '#ffffff',
				overlayOpacity: 0,
				overlayHoverBackgroundColor: '#06c19d',
				overlayHoverOpacity: 0.8,
				imageHoverEffect: 'zoom-in',
				showSubtitle: false,
				subtitleFontFamily: 'Roboto Condensed',
				subtitleFontWeight: '400',
				subtitleLetterSpacing: 0.5,
				subtitleColor: '#ffffff',
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleColor: '#ffffff',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				arrowColor: '#728a23',
				paddingTop: 130,
				paddingBottom: 130,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#707070',
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#06c19d',
				blockDescriptionBottomMargin: 50,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
	}
} )
