export default {
	clientId: '8b60d048-b614-4c6e-9926-33ed5237ea4f', name: 'stackable/image-box', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-image-box is-style-default stk-block-image-box stk-hover-parent stk-block stk-e65ffe4" data-block-id="e65ffe4"><div class="stk-block-content stk-inner-blocks has-text-align-center stk-row stk-block-image-box__content">\n\n</div></div>', attributes: {
		uniqueId: 'e65ffe4', hasBackground: false, hasBorders: false, contentAlign: 'center', effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', className: 'is-style-default',
	}, innerBlocks: [ {
		clientId: '03df127f-3de0-406a-9644-13e40b4bdcff', name: 'stackable/image', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-image stk-block-image stk-block stk-f45cd4f" data-block-id="f45cd4f"><style>:where(.stk-hover-parent:hover,.stk-hover-parent.stk--is-hovered) .stk-f45cd4f .stk-img-wrapper img{filter:brightness(0.3) !important}.stk-f45cd4f .stk-img-wrapper{height:350px !important}</style><figure class="stk-img-wrapper stk-image--shape-stretch"><img class="stk-img" src="https://source.unsplash.com/400x300/?shoes" width="150" height="350"/></figure></div>', attributes: {
			uniqueId: 'f45cd4f', hasBackground: false, hasBorders: false, imageShow: true, imageUrl: 'https://source.unsplash.com/400x300/?shoes', imageSize: 'full', imageHeight: 350, imageShapeStretch: true, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', imageWidthUnit: '%', imageWidthUnitTablet: '%', imageWidthUnitMobile: '%', imageFilterParentHover: 'brightness(0.3)',
		}, innerBlocks: [],
	}, {
		clientId: 'ddba5084-b3c1-44e0-aedb-1b0e51375bd7', name: 'stackable/column', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-column stk-block-column stk-column stk-block stk-cd5f242" data-block-id="cd5f242"><div class="stk-block-content stk-inner-blocks stk-column-wrapper stk-block-column__content stk-container stk-cd5f242-container stk--no-background stk--no-padding"></div></div>', attributes: {
			uniqueId: 'cd5f242', hasBackground: false, hasBorders: false, hasContainer: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', containerBackgroundCustomSizeUnit: '%', containerBackgroundCustomSizeUnitTablet: '%', containerBackgroundCustomSizeUnitMobile: '%',
		}, innerBlocks: [ {
			clientId: '7de9186d-95bb-43ef-807b-9bdfe9095013', name: 'stackable/heading', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-heading stk-block-heading stk-block stk-889b5d9" data-block-id="889b5d9"><h4 class="stk-block-heading__text">Title</h4></div>', attributes: {
				uniqueId: '889b5d9', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Title', textTag: 'h4', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		} ],
	} ],
}
