export default {
	design: 'basic',
	onlyOnePanelOpen: false,
	openStart: true,
	reverseArrow: false,
	containerBackgroundCustomSizeUnit: '%',
	containerTabletBackgroundCustomSizeUnit: '%',
	containerMobileBackgroundCustomSizeUnit: '%',
	title: 'Title for This Block',
	showTitle: true,
	titleLineHeightUnit: 'em',
	titleTabletLineHeightUnit: 'em',
	titleMobileLineHeightUnit: 'em',
	showArrow: true,
	showBorder: true,
	uniqueClass: 'ugb-872a8ec',
	hideDesktop: false,
	hideTablet: false,
	hideMobile: false,
}
