export default {
	design: 'basic',
	invert: false,
	columnBackgroundCustomSizeUnit: '%',
	columnTabletBackgroundCustomSizeUnit: '%',
	columnMobileBackgroundCustomSizeUnit: '%',
	imageSize: 'large',
	imageShapeStretch: true,
	title: 'Title for This Block',
	showTitle: true,
	titleLineHeightUnit: 'em',
	titleTabletLineHeightUnit: 'em',
	titleMobileLineHeightUnit: 'em',
	description: 'Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.',
	showDescription: true,
	descriptionLineHeightUnit: 'em',
	descriptionTabletLineHeightUnit: 'em',
	descriptionMobileLineHeightUnit: 'em',
	showButton: true,
	buttonLineHeightUnit: 'em',
	buttonTabletLineHeightUnit: 'em',
	buttonMobileLineHeightUnit: 'em',
	buttonText: 'Button text',
	buttonNewTab: false,
	uniqueClass: 'ugb-5bae7c2',
	hideDesktop: false,
	hideTablet: false,
	hideMobile: false,
	showBlockBackground: false,
	blockBackgroundBackgroundCustomSizeUnit: '%',
	blockBackgroundTabletBackgroundCustomSizeUnit: '%',
	blockBackgroundMobileBackgroundCustomSizeUnit: '%',
	topSeparatorDesign: 'wave-1',
	bottomSeparatorDesign: 'wave-1',
	topSeparatorShadow: true,
	bottomSeparatorShadow: true,
}
