export default {
	attributes: {
		design: 'plain',
		columns: 2,
		columns1: 50,
		columns2: 50,
		hideDesktop: false,
		hideTablet: false,
		hideMobile: false,
		showBlockBackground: false,
		blockBackgroundBackgroundCustomSizeUnit: '%',
		blockBackgroundTabletBackgroundCustomSizeUnit: '%',
		blockBackgroundMobileBackgroundCustomSizeUnit: '%',
		topSeparatorDesign: 'wave-1',
		bottomSeparatorDesign: 'wave-1',
		topSeparatorShadow: true,
		bottomSeparatorShadow: true,
		showBlockTitle: false,
		blockTitleLineHeightUnit: 'em',
		blockTitleTabletLineHeightUnit: 'em',
		blockTitleMobileLineHeightUnit: 'em',
		showBlockDescription: false,
		blockDescriptionLineHeightUnit: 'em',
		blockDescriptionTabletLineHeightUnit: 'em',
		blockDescriptionMobileLineHeightUnit: 'em',
	}, innerBlocks: [ {
		clientId: 'fcd43dcf-7982-441c-aa3c-c5c408328324',
		name: 'ugb/column',
		isValid: true,
		validationIssues: [],
		originalContent: '<div class="wp-block-ugb-column ugb-column ugb-0add602 ugb-column--design-plain ugb-main-block"><div class="ugb-inner-block"><div class="ugb-block-content"><div class="ugb-column__item ugb-0add602-column-wrapper"><div class="ugb-column__content-wrapper">\n\n</div></div></div></div></div>',
		attributes: {
			design: 'plain',
			columnBackgroundCustomSizeUnit: '%',
			columnTabletBackgroundCustomSizeUnit: '%',
			columnMobileBackgroundCustomSizeUnit: '%',
		}, innerBlocks: [ {
			clientId: 'de4a5742-7cf3-4685-b3d7-be00148d543c',
			name: 'ugb/text',
			isValid: true,
			validationIssues: [],
			originalContent: '<div class="wp-block-ugb-text ugb-text ugb-d6f183b ugb-text--design-plain ugb-text--columns-1 ugb-main-block"><style>.ugb-d6f183b .ugb-text__title{margin-bottom:0px !important}</style><div class="ugb-inner-block"><div class="ugb-block-content"><div class="ugb-text__title-wrapper"><h2 class="ugb-text__title">Block Title</h2></div><div class="ugb-text__text-wrapper"><div class="ugb-text__text"><p class="ugb-text__text-1">Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.</p></div></div></div></div></div>', attributes: {
				design: 'plain',
				columns: 1,
				reverseTitle: false,
				alignment: 'center',
				showColumnRule: false,
				showTitle: true,
				title: 'Block Title',
				titleLineHeightUnit: 'em',
				titleTabletLineHeightUnit: 'em',
				titleMobileLineHeightUnit: 'em',
				showSubtitle: false,
				subtitleLineHeightUnit: 'em',
				subtitleTabletLineHeightUnit: 'em',
				subtitleMobileLineHeightUnit: 'em',
				subtitleOnTop: false,
				text1: 'Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.',
				textLineHeightUnit: 'em',
				textTabletLineHeightUnit: 'em',
				textMobileLineHeightUnit: 'em',
				titleBottomMargin: 0,
				blockBackgroundBackgroundCustomSizeUnit: '%',
				blockBackgroundTabletBackgroundCustomSizeUnit: '%',
				blockBackgroundMobileBackgroundCustomSizeUnit: '%',
				topSeparatorDesign: 'wave-1',
				bottomSeparatorDesign: 'wave-1',
			}, innerBlocks: [],
		}, {
			clientId: '6774f0af-2b98-4073-8de4-86b456d8088b',
			name: 'ugb/icon-list',
			isValid: true,
			validationIssues: [],
			originalContent: "<div class=\"wp-block-ugb-icon-list ugb-icon-list ugb-db1078a ugb-icon-list--v2 ugb-main-block\"><style>.ugb-db1078a li::before{background-image:url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTAgMTkwIj48cG9seWdvbiBwb2ludHM9IjE3My44LDI4LjQgNjAuNCwxNDEuOCAxNS43LDk3LjIgNS4xLDEwNy44IDYwLjQsMTYzIDE4NC40LDM5IDE3My44LDI4LjQiLz48L3N2Zz4=')}.ugb-db1078a.ugb-icon-list ul{columns:2}</style><div class=\"ugb-inner-block\"><div class=\"ugb-block-content\"><ul><li>Line 1</li><li>Line 2</li><li>Line 3</li><li>Line 4</li><li>Line 5</li><li>Line 6</li></ul></div></div></div>", attributes: {
				icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 190 190"><polygon points="173.8,28.4 60.4,141.8 15.7,97.2 5.1,107.8 60.4,163 184.4,39 173.8,28.4"/></svg>',
				columns: 2,
				text: '<li>Line 1</li><li>Line 2</li><li>Line 3</li><li>Line 4</li><li>Line 5</li><li>Line 6</li>', displayAsGrid: false,
				listTextLineHeightUnit: 'em',
				listTextTabletLineHeightUnit: 'em',
				listTextMobileLineHeightUnit: 'em',
				blockBackgroundBackgroundCustomSizeUnit: '%',
				blockBackgroundTabletBackgroundCustomSizeUnit: '%',
				blockBackgroundMobileBackgroundCustomSizeUnit: '%',
			}, innerBlocks: [],
		} ],
	}, {
		clientId: 'e23821b4-6774-4a50-8d82-3751751ef825',
		name: 'ugb/column',
		isValid: true,
		validationIssues: [],
		originalContent: '<div class="wp-block-ugb-column ugb-column ugb-e6493d1 ugb-column--design-plain ugb-main-block"><div class="ugb-inner-block"><div class="ugb-block-content"><div class="ugb-column__item ugb-e6493d1-column-wrapper ugb--has-background-overlay"><div class="ugb-column__content-wrapper"></div></div></div></div></div>',
		attributes: {
			design: 'plain',
			columnBackgroundMediaUrl: 'http://sandbox.gambit.ph/bea/wp-content/uploads/sites/59/2020/09/aaron-burden-cEukkv42O40-unsplash.jpg',
		}, innerBlocks: [ {
			clientId: '3b7cc2c3-7048-454e-828e-5f43ac2d8f0d',
			name: 'core/image',
			isValid: true,
			validationIssues: [],
			originalContent: '<figure class="wp-block-image size-large"><img src="http://sandbox.gambit.ph/bea/wp-content/uploads/sites/59/2020/08/stephan-schmid-eMwpXxbQcAM-unsplash.jpg" alt="" class="wp-image-257" /></figure>', attributes: {
				url: 'http://sandbox.gambit.ph/bea/wp-content/uploads/sites/59/2020/08/stephan-schmid-eMwpXxbQcAM-unsplash.jpg',
				caption: '',
				id: 257,
				sizeSlug: 'large',
				linkDestination: 'none',
			}, innerBlocks: [],
		} ],
	} ],
}
