export default {
	attributes: {
		design: 'plain',
		columns: 2,
		columns1: 50,
		columns2: 50,
		hideDesktop: false,
		hideTablet: false,
		hideMobile: false,
		showBlockBackground: false,
		blockBackgroundBackgroundCustomSizeUnit: '%',
		blockBackgroundTabletBackgroundCustomSizeUnit: '%',
		blockBackgroundMobileBackgroundCustomSizeUnit: '%',
		topSeparatorDesign: 'wave-1',
		bottomSeparatorDesign: 'wave-1',
		topSeparatorShadow: true,
		bottomSeparatorShadow: true,
		showBlockTitle: false,
		blockTitleLineHeightUnit: 'em',
		blockTitleTabletLineHeightUnit: 'em',
		blockTitleMobileLineHeightUnit: 'em',
		showBlockDescription: false,
		blockDescriptionLineHeightUnit: 'em',
		blockDescriptionTabletLineHeightUnit: 'em',
		blockDescriptionMobileLineHeightUnit: 'em',
	}, innerBlocks: [ {
		clientId: 'fcd43dcf-7982-441c-aa3c-c5c408328324',
		name: 'ugb/column',
		isValid: true,
		validationIssues: [],
		originalContent: '<div class="wp-block-ugb-column ugb-column ugb-0add602 ugb-column--design-plain ugb-main-block"><div class="ugb-inner-block"><div class="ugb-block-content"><div class="ugb-column__item ugb-0add602-column-wrapper"><div class="ugb-column__content-wrapper">\n\n</div></div></div></div></div>',
		attributes: {
			design: 'basic',
			columnBackgroundCustomSizeUnit: '%',
			columnTabletBackgroundCustomSizeUnit: '%',
			columnMobileBackgroundCustomSizeUnit: '%',
		},
	}, {
		clientId: 'e23821b4-6774-4a50-8d82-3751751ef825',
		name: 'ugb/column',
		isValid: true,
		validationIssues: [],
		originalContent: '<div class="wp-block-ugb-column ugb-column ugb-e6493d1 ugb-column--design-plain ugb-main-block"><div class="ugb-inner-block"><div class="ugb-block-content"><div class="ugb-column__item ugb-e6493d1-column-wrapper ugb--has-background-overlay"><div class="ugb-column__content-wrapper"></div></div></div></div></div>',
		attributes: {
			design: 'basic',
		},
	} ],
}
