export default {
	icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 190 190"><polygon points="173.8,28.4 60.4,141.8 15.7,97.2 5.1,107.8 60.4,163 184.4,39 173.8,28.4"/></svg>',
	columns: 2,
	text: '<li>Line 1</li><li>Line 2</li><li>Line 3</li><li>Line 4</li><li>Line 5</li><li>Line 6</li>',
	displayAsGrid: false,
	listTextLineHeightUnit: 'em',
	listTextTabletLineHeightUnit: 'em',
	listTextMobileLineHeightUnit: 'em',
	uniqueClass: 'ugb-495b710',
	hideDesktop: false,
	hideTablet: false,
	hideMobile: false,
	showBlockBackground: false,
	blockBackgroundBackgroundCustomSizeUnit: '%',
	blockBackgroundTabletBackgroundCustomSizeUnit: '%',
	blockBackgroundMobileBackgroundCustomSizeUnit: '%',
	topSeparatorDesign: 'wave-1',
	bottomSeparatorDesign: 'wave-1',
	topSeparatorShadow: true,
	bottomSeparatorShadow: true,
	showBlockTitle: false,
	blockTitleLineHeightUnit: 'em',
	blockTitleTabletLineHeightUnit: 'em',
	blockTitleMobileLineHeightUnit: 'em',
	showBlockDescription: false,
	blockDescriptionLineHeightUnit: 'em',
	blockDescriptionTabletLineHeightUnit: 'em',
	blockDescriptionMobileLineHeightUnit: 'em',
}
