export default {
	num1: '01',
	num2: '02',
	title1: 'Title',
	title2: 'Title',
	description1: 'Description for this block. Use this space for describing your block. Any text will do.',
	description2: 'Description for this block. Use this space for describing your block. Any text will do.',
	columns: 2,
	design: 'basic',
	columnBackgroundCustomSizeUnit: '%',
	columnTabletBackgroundCustomSizeUnit: '%',
	columnMobileBackgroundCustomSizeUnit: '%',
	showNumber: true,
	numberLineHeightUnit: 'em',
	numberTabletLineHeightUnit: 'em',
	numberMobileLineHeightUnit: 'em',
	showTitle: true,
	titleLineHeightUnit: 'em',
	titleTabletLineHeightUnit: 'em',
	titleMobileLineHeightUnit: 'em',
	showDescription: true,
	descriptionLineHeightUnit: 'em',
	descriptionTabletLineHeightUnit: 'em',
	descriptionMobileLineHeightUnit: 'em',
	uniqueClass: 'ugb-5cb0010',
	hideDesktop: false,
	hideTablet: false,
	hideMobile: false,
	showBlockBackground: false,
	blockBackgroundBackgroundCustomSizeUnit: '%',
	blockBackgroundTabletBackgroundCustomSizeUnit: '%',
	blockBackgroundMobileBackgroundCustomSizeUnit: '%',
	topSeparatorDesign: 'wave-1',
	bottomSeparatorDesign: 'wave-1',
	topSeparatorShadow: true,
	bottomSeparatorShadow: true,
	showBlockTitle: false,
	blockTitleLineHeightUnit: 'em',
	blockTitleTabletLineHeightUnit: 'em',
	blockTitleMobileLineHeightUnit: 'em',
	showBlockDescription: false,
	blockDescriptionLineHeightUnit: 'em',
	blockDescriptionTabletLineHeightUnit: 'em',
	blockDescriptionMobileLineHeightUnit: 'em',
}
