/**
 * External dependencies
 */
import { omit } from 'lodash'
import { i18n } from 'stackable'

/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n'
import { addFilter } from '@wordpress/hooks'

// Remove text from block designs being applied.
addFilter( 'stackable.testimonial.design.no-text-attributes', 'stackable/testimonial', attributes => {
	return omit( attributes, [
		'testimonial1',
		'testimonial2',
		'testimonial3',
		'name1',
		'name2',
		'name3',
		'position1',
		'position2',
		'position3',
	] )
} )

// Ignore these attributes when exporting / applying designs.
addFilter( 'stackable.testimonial.design.filtered-block-attributes', 'stackable/testimonial', ( attributes, blockAttributes = null ) => {
	return omit( attributes, [
		'image1Id',
		...( blockAttributes && blockAttributes.image1Id ? [ 'image1Url' ] : [] ),
		'image2Id',
		...( blockAttributes && blockAttributes.image2Id ? [ 'image2Url' ] : [] ),
		'image3Id',
		...( blockAttributes && blockAttributes.image3Id ? [ 'image3Url' ] : [] ),
		'image1Alt',
		'image2Alt',
		'image3Alt',
	] )
} )

addFilter( 'stackable.testimonial.edit.designs', 'stackable/testimonial', designs => {
	return {
		...designs,
		corporateLight1: {
			label: __( 'Corporate Light 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-testimonial-design-corporate-light-01.jpg',
			attributes: {
				borderRadius: 0,
				columns: 3,
				columnBackgroundColorOpacity: 0.8,
				testimonialFontFamily: 'Serif',
				testimonialColor: '#707070',
				showImage: false,
				nameFontFamily: 'Roboto Condensed',
				nameFontWeight: '100',
				nameLetterSpacing: 0.5,
				nameColor: '#ff550a',
				positionFontFamily: 'Roboto',
				positionColor: '#ffb20b',
				testimonialAlign: 'center',
				imageAlign: 'center',
				nameAlign: 'center',
				positionAlign: 'center',
				testimonialBottomMargin: 40,
				paddingTop: 100,
				paddingBottom: 100,
				columnGap: 100,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColorType: 'gradient',
				blockBackgroundBackgroundColor: '#ff550a',
				blockBackgroundBackgroundColor2: '#ffb20b',
				blockBackgroundBackgroundMediaUrl: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-image-box-corporate-light-01-01.jpg',
				blockBackgroundBackgroundTintStrength: 8,
				blockBackgroundBackgroundGradientDirection: 180,
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#ffffff',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
		corporateLight2: {
			label: __( 'Corporate Light 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-testimonial-design-corporate-light-02.jpg',
			attributes: {
				borderRadius: 0,
				columns: 3,
				columnBackgroundColorOpacity: 0.8,
				testimonialFontFamily: 'Serif',
				testimonialColor: '#707070',
				showImage: false,
				nameFontFamily: 'Roboto Condensed',
				nameFontWeight: '100',
				nameLetterSpacing: 0.5,
				nameColor: '#1e55d3',
				positionFontFamily: 'Roboto',
				positionColor: '#c49732',
				testimonialAlign: 'center',
				imageAlign: 'center',
				nameAlign: 'center',
				positionAlign: 'center',
				testimonialBottomMargin: 40,
				paddingTop: 100,
				paddingBottom: 100,
				columnGap: 100,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#1142b2',
				blockBackgroundBackgroundColor2: '#ffb20b',
				blockBackgroundBackgroundMediaUrl: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-testimonial-corporate-light-02-01.jpg',
				blockBackgroundBackgroundTintStrength: 6,
				blockBackgroundBackgroundGradientDirection: 180,
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#ffffff',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
		corporateDark1: {
			label: __( 'Corporate Dark 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-testimonial-design-corporate-dark-01.jpg',
			attributes: {
				design: 'plain',
				columns: 3,
				testimonialFontFamily: 'Serif',
				testimonialColor: '#ffffff',
				showImage: false,
				nameFontFamily: 'Roboto Condensed',
				nameFontWeight: '100',
				nameLetterSpacing: 0.5,
				nameColor: '#c5dfb4',
				positionFontFamily: 'Roboto',
				positionColor: '#ffffff',
				testimonialAlign: 'center',
				imageAlign: 'center',
				nameAlign: 'center',
				positionAlign: 'center',
				testimonialBottomMargin: 40,
				paddingTop: 100,
				paddingBottom: 100,
				columnGap: 100,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#0e2448',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#c5dfb4',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
		corporateDark2: {
			label: __( 'Corporate Dark 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-testimonial-design-corporate-dark-02.jpg',
			attributes: {
				design: 'plain',
				columns: 3,
				testimonialFontFamily: 'Serif',
				testimonialColor: '#ffffff',
				showImage: false,
				nameFontFamily: 'Roboto Condensed',
				nameFontWeight: '100',
				nameLetterSpacing: 0.5,
				nameColor: '#06c19d',
				positionFontFamily: 'Roboto',
				positionColor: '#a3ffed',
				testimonialAlign: 'center',
				imageAlign: 'center',
				nameAlign: 'center',
				positionAlign: 'center',
				testimonialBottomMargin: 40,
				paddingTop: 100,
				paddingBottom: 100,
				columnGap: 100,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#2f2f2f',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#06c19d',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
	}
} )
