export default {
	clientId: 'cd158f31-df35-400a-b002-dfa8ec585bba', name: 'stackable/testimonial', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-testimonial is-style-default stk-block-testimonial stk-block stk-827f26e" data-block-id="827f26e"><div class="stk-block-content stk-inner-blocks has-text-align-center stk-block-testimonial__content stk-content-align stk-container stk-827f26e-container stk-hover-parent">\n\n\n\n\n\n</div></div>', attributes: {
		uniqueId: '827f26e', hasBackground: false, hasBorders: false, hasContainer: true, contentAlign: 'center', effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], displayCondition: {}, hideDesktop: false, hideTablet: false, hideMobile: false, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', containerBackgroundCustomSizeUnit: '%', containerBackgroundCustomSizeUnitTablet: '%', containerBackgroundCustomSizeUnitMobile: '%', className: 'is-style-default',
	}, innerBlocks: [ {
		clientId: 'f782efee-690f-4d59-80c0-c96e2929ae2e', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-text stk-block-text stk-block stk-a452770" data-block-id="a452770"><p class="stk-block-text__text">Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.</p></div>', attributes: {
			uniqueId: 'a452770', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: '7356ffac-d4e7-4766-811f-a8a49653adf9', name: 'stackable/image', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-image stk-block-image stk-block stk-9f4c781" data-block-id="9f4c781"><style>.stk-9f4c781 .stk-img-wrapper{width:75px !important;height:75px !important;border-radius:90px !important}</style><figure class="stk-img-wrapper stk-image--shape-stretch"><img class="stk-img" src="https://source.unsplash.com/300x300/?selfie" width="75" height="75"/></figure></div>', attributes: {
			uniqueId: '9f4c781', hasBackground: false, hasBorders: false, imageShow: true, imageUrl: 'https://source.unsplash.com/300x300/?selfie', imageSize: 'full', imageBorderRadius: 90, imageHeight: 75, imageWidth: 75, imageShapeStretch: true, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', imageWidthUnitTablet: '%', imageWidthUnitMobile: '%', imageWidthUnit: 'px',
		}, innerBlocks: [],
	}, {
		clientId: '4db3f8dd-1b3c-431c-9de2-f49faedf1e19', name: 'stackable/heading', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-heading stk-block-heading stk-block stk-3688a95" data-block-id="3688a95"><style>.stk-3688a95 .stk-block-heading__text{margin:0 !important}</style><h3 class="stk-block-heading__text">Name</h3></div>', attributes: {
			uniqueId: '3688a95', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, textRemoveTextMargins: true, hasP: false, show: true, showText: true, text: 'Name', textTag: 'h3', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: '5486705a-e6fb-44de-8893-b283cde831a4', name: 'stackable/subtitle', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-subtitle stk-block-subtitle stk-block stk-8dba7d3" data-block-id="8dba7d3"><p class="stk-block-subtitle__text stk-subtitle">Position</p></div>', attributes: {
			uniqueId: '8dba7d3', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Position', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	} ],
}
