/**
 * External dependencies
 */
import { omit } from 'lodash'
import { i18n } from 'stackable'

/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n'
import { addFilter } from '@wordpress/hooks'

addFilter( 'stackable.pricing-box.design.apply-block-attributes', 'stackable/pricing-box', ( attributes, blockAttributes = null ) => {
	return omit( attributes, [
		'image1Id',
		...( blockAttributes && blockAttributes.image1Id ? [ 'image1Url' ] : [] ),
		'image2Id',
		...( blockAttributes && blockAttributes.image2Id ? [ 'image2Url' ] : [] ),
		'image3Id',
		...( blockAttributes && blockAttributes.image3Id ? [ 'image3Url' ] : [] ),
		'image1Alt',
		'image2Alt',
		'image3Alt',
		'title1',
		'title2',
		'title3',
		'pricePrefix1',
		'pricePrefix2',
		'pricePrefix3',
		'price1',
		'price2',
		'price3',
		'priceSuffix1',
		'priceSuffix2',
		'priceSuffix3',
		'subPrice1',
		'subPrice2',
		'subPrice3',
		'button1Text',
		'button1Url',
		'button1NewTab',
		'button1NoFollow',
		'button2Text',
		'button2Url',
		'button2NewTab',
		'button2NoFollow',
		'button3Text',
		'button3Url',
		'button3NewTab',
		'button3NoFollow',
		'description1',
		'description2',
		'description3',
	] )
} )

addFilter( 'stackable.pricing-box.edit.designs', 'stackable/pricing-box', designs => {
	return {
		...designs,
		corporateLight1: {
			label: __( 'Corporate Light 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-pricing-design-corporate-light-01.jpg',
			attributes: {
				borderRadius: 0,
				shadow: 0,
				columnBackgroundColor: '#ffb20b',
				columnBackgroundColorOpacity: 0.8,
				showImage: false,
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleColor: '#ff550a',
				priceFontFamily: 'Roboto',
				priceFontWeight: 'bold',
				priceColor: '#ffffff',
				subPriceFontFamily: 'Roboto',
				subPriceColor: '#ff550a',
				buttonFontFamily: 'Roboto Condensed',
				buttonFontWeight: '400',
				buttonLetterSpacing: 0.5,
				buttonDesign: 'ghost',
				buttonSize: 'small',
				buttonTextColor: '#3f4174',
				buttonBackgroundColor: '#ff550a',
				buttonHoverEffect: 'lift',
				buttonBorderRadius: 100,
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				paddingTop: 130,
				paddingBottom: 130,
				columnPaddingRight: 60,
				columnPaddingLeft: 60,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#ffffff',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#ffb20b',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#707070',
			},
		},
		corporateLight2: {
			label: __( 'Corporate Light 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-pricing-design-corporate-light-02.jpg',
			attributes: {
				borderRadius: 0,
				shadow: 0,
				columnBackgroundColor: '#6a91eb',
				columnBackgroundColorOpacity: 0.8,
				showImage: false,
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleColor: '#ffffff',
				priceFontFamily: 'Roboto',
				priceFontWeight: 'bold',
				priceColor: '#1e55d3',
				subPriceFontFamily: 'Roboto',
				subPriceColor: '#1e55d3',
				buttonFontFamily: 'Roboto Condensed',
				buttonFontWeight: '400',
				buttonLetterSpacing: 0.5,
				buttonDesign: 'basic',
				buttonSize: 'small',
				buttonTextColor: '#ffffff',
				buttonBackgroundColor: '#c49732',
				buttonHoverEffect: 'lift',
				buttonBorderRadius: 100,
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				paddingTop: 130,
				paddingBottom: 130,
				columnPaddingRight: 60,
				columnPaddingLeft: 60,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#ffffff',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#c49732',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#707070',
			},
		},
		corporateDark1: {
			label: __( 'Corporate Dark 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-pricing-design-corporate-dark-01.jpg',
			attributes: {
				borderRadius: 0,
				shadow: 0,
				columnBackgroundColor: '#0c4887',
				columnBackgroundColorOpacity: 0.8,
				showImage: false,
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleColor: '#c5dfb4',
				priceFontFamily: 'Roboto',
				priceFontWeight: 'bold',
				priceColor: '#ffffff',
				subPriceFontFamily: 'Roboto',
				subPriceColor: '#ffffff',
				buttonFontFamily: 'Roboto Condensed',
				buttonFontWeight: '400',
				buttonLetterSpacing: 0.5,
				buttonSize: 'small',
				buttonTextColor: '#3f4174',
				buttonBackgroundColor: '#c4e558',
				buttonHoverEffect: 'lift',
				buttonBorderRadius: 100,
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				paddingTop: 130,
				paddingBottom: 130,
				columnPaddingRight: 60,
				columnPaddingLeft: 60,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundMediaUrl: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-header-corporate-dark-01-01.jpg',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#c5dfb4',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
		corporateDark2: {
			label: __( 'Corporate Dark 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-pricing-design-corporate-dark-02.jpg',
			attributes: {
				borderRadius: 0,
				shadow: 0,
				columnBackgroundColor: '#2f2f2f',
				columnBackgroundColorOpacity: 0.8,
				showImage: false,
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleColor: '#06c19d',
				priceFontFamily: 'Roboto',
				priceFontWeight: 'bold',
				priceColor: '#ffffff',
				subPriceFontFamily: 'Roboto',
				subPriceColor: '#06c19d',
				buttonFontFamily: 'Roboto Condensed',
				buttonFontWeight: '400',
				buttonLetterSpacing: 0.5,
				buttonDesign: 'ghost',
				buttonSize: 'small',
				buttonTextColor: '#ffffff',
				buttonBackgroundColor: '#06c19d',
				buttonHoverEffect: 'lift',
				buttonBorderRadius: 100,
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				paddingTop: 130,
				paddingBottom: 130,
				columnPaddingRight: 60,
				columnPaddingLeft: 60,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#000000',
				blockBackgroundBackgroundMediaUrl: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-corporate-dark-02-01.jpg',
				blockBackgroundBackgroundTintStrength: 4,
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#06c19d',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
	}
} )
