export default {
	clientId: 'c55ec129-8171-46e6-8625-1ab7d5774804', name: 'stackable/pricing-box', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-pricing-box is-style-basic stk-block-pricing-box stk-block stk-093422b" data-block-id="093422b"><div class="stk-block-content stk-inner-blocks has-text-align-center stk-block-pricing-box__content stk-content-align stk-container stk-093422b-container stk-hover-parent">\n\n\n\n\n\n\n\n</div></div>', attributes: {
		uniqueId: '093422b', hasBackground: false, hasBorders: false, hasContainer: true, contentAlign: 'center', effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], displayCondition: {}, hideDesktop: false, hideTablet: false, hideMobile: false, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', containerBackgroundCustomSizeUnit: '%', containerBackgroundCustomSizeUnitTablet: '%', containerBackgroundCustomSizeUnitMobile: '%', className: 'is-style-basic',
	}, innerBlocks: [ {
		clientId: '75ac2ba8-36dd-4cbf-813c-ad2041b8b296', name: 'stackable/heading', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-heading stk-block-heading stk-block stk-5012c51" data-block-id="5012c51"><style>.stk-5012c51 .stk-block-heading__text{margin:0 !important}</style><h3 class="stk-block-heading__text">Title</h3></div>', attributes: {
			uniqueId: '5012c51', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, textRemoveTextMargins: true, hasP: false, show: true, showText: true, text: 'Title', textTag: 'h3', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: '03476ca8-5ff2-4a4a-8405-45506780db9c', name: 'stackable/price', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-price stk-block-price stk-block stk-9de41dd" data-block-id="9de41dd">\n\n\n\n</div>', attributes: {
			uniqueId: '9de41dd', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%',
		}, innerBlocks: [ {
			clientId: 'e9e139f8-7b6f-4546-a07c-9934a6608e03', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<span class="wp-block-stackable-text stk-block-text stk-block stk-8268936" data-block-id="8268936"><span class="stk-block-text__text">$</span></span>', attributes: {
				uniqueId: '8268936', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, htmlTag: 'span', hasP: false, show: true, showText: true, text: '$', innerTextTag: 'span', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		}, {
			clientId: '6a3c0876-0842-45d9-b047-4d5ee054059f', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<span class="wp-block-stackable-text stk-block-price__price stk-block-text stk-block stk-e63a742" data-block-id="e63a742"><span class="stk-block-text__text">99</span></span>', attributes: {
				uniqueId: 'e63a742', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, htmlTag: 'span', hasP: false, show: true, showText: true, text: '99', innerTextTag: 'span', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em', className: 'stk-block-price__price',
			}, innerBlocks: [],
		}, {
			clientId: '30623404-c323-42ef-9287-4a71fe7c2e19', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<span class="wp-block-stackable-text stk-block-text stk-block stk-cb8d508" data-block-id="cb8d508"><span class="stk-block-text__text">.00</span></span>', attributes: {
				uniqueId: 'cb8d508', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, htmlTag: 'span', hasP: false, show: true, showText: true, text: '.00', innerTextTag: 'span', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		} ],
	}, {
		clientId: '852fa3f5-acc0-4a39-a93e-e2a9ec274877', name: 'stackable/subtitle', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-subtitle stk-block-subtitle stk-block stk-f466288" data-block-id="f466288"><p class="stk-block-subtitle__text stk-subtitle">Subtitle for This Block</p></div>', attributes: {
			uniqueId: 'f466288', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Subtitle for This Block', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: '2fae33b6-70f2-4df9-9d26-fc9bff48aa15', name: 'stackable/icon-list', isValid: true, validationIssues: [], originalContent: "<div class=\"wp-block-stackable-icon-list stk-block-icon-list stk-block stk-438b4fe\" data-block-id=\"438b4fe\"><style>.stk-438b4fe li{list-style-image:url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTAgMTkwIiBzdHlsZT0iZmlsbDogIzAwMCAhaW1wb3J0YW50OyBjb2xvcjogIzAwMCAhaW1wb3J0YW50O3RyYW5zZm9ybTogcm90YXRlKGRlZykgIWltcG9ydGFudDsiPjxwb2x5Z29uIHBvaW50cz0iMTczLjgsMjguNCA2MC40LDE0MS44IDE1LjcsOTcuMiA1LjEsMTA3LjggNjAuNCwxNjMgMTg0LjQsMzkgMTczLjgsMjguNCIgZmlsbD0iIzAwMCIgc3Ryb2tlPSIjMDAwIiBzdHlsZT0iZmlsbDogcmdiKDAsIDAsIDApOyBzdHJva2U6IHJnYigwLCAwLCAwKTsiLz48L3N2Zz4=') !important}</style><ul><li>Package inclusion one</li><li>Package inclusion two</li><li>Package inclusion three</li></ul></div>", attributes: {
			uniqueId: '438b4fe', hasBackground: false, hasBorders: false, customAttributes: [], effectAnimationOut: {}, effectAnimationIn: {}, hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: '<li>Package inclusion one</li><li>Package inclusion two</li><li>Package inclusion three</li>', ordered: false, icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 190 190"><polygon points="173.8,28.4 60.4,141.8 15.7,97.2 5.1,107.8 60.4,163 184.4,39 173.8,28.4"/></svg>', icons: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em', contentAlign: 'center',
		}, innerBlocks: [],
	}, {
		clientId: '6967c080-1c4d-4b18-9871-396ea89cd2d1', name: 'stackable/button-group', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button-group stk-block-button-group stk-block stk-7fdb95b" data-block-id="7fdb95b"><div class="stk-row stk-inner-blocks stk-block-content stk-button-group"></div></div>', attributes: {
			uniqueId: '7fdb95b', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%',
		}, innerBlocks: [ {
			clientId: '8f1035a0-2c33-4a54-95e4-a4517ac6c0f9', name: 'stackable/button', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button stk-block-button stk-block stk-fe3d631" data-block-id="fe3d631"><a class="stk-link stk-button" href=""><span class="stk-button__inner-text">Button</span></a></div>', attributes: {
				uniqueId: 'fe3d631', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, linkHasLink: true, linkNewTab: false, linkHasTitle: true, showBackgroundShape: false, hasP: false, show: true, showText: true, text: 'Button', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		} ],
	} ],
}
