// HOCs for edit components.
export { default as withBlockStyles } from './with-block-styles'
export { default as withContentAlignReseter } from './with-content-align-reseter'
export { default as withGoogleFont } from './with-google-font'
export { default as withMainClassname } from './with-main-classname'
export { default as withSetAttributeHook } from './with-set-attribute-hook'
export { default as withTabbedInspector } from './with-tabbed-inspector'
export { default as withUniqueClass } from './with-unique-class'
export { default as withClickOpenInspector } from './with-click-open-inspector'
export { default as withHelpTip } from './with-help-tip'
