export default {
	clientId: 'a7f21c05-ca7f-48fb-9117-d9d45e16c125', name: 'stackable/card', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-card is-style-default stk-block-card stk-block stk-fce02f9" data-block-id="fce02f9"><div class="stk-block-content stk--no-padding stk-container stk-fce02f9-container stk-hover-parent"><figure class="stk-block-card__image stk-img-wrapper stk-image--shape-stretch"><img class="stk-img" src="https://source.unsplash.com/400x300/?abstract" width="150" height="300"/></figure><div class="stk-inner-blocks stk-block-card__content stk-container-padding">\n\n\n\n\n\n</div></div></div>', attributes: {
		uniqueId: 'fce02f9', hasBackground: false, hasBorders: false, hasContainer: true, imageShow: true, imageUrl: 'https://source.unsplash.com/400x300/?abstract', imageSize: 'full', imageShapeStretch: true, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', containerBackgroundCustomSizeUnit: '%', containerBackgroundCustomSizeUnitTablet: '%', containerBackgroundCustomSizeUnitMobile: '%', className: 'is-style-default',
	}, innerBlocks: [ {
		clientId: 'd80935f5-e465-4d27-bb64-3f46ae33b5dd', name: 'stackable/heading', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-heading stk-block-heading stk-block stk-b72d337" data-block-id="b72d337"><h2 class="stk-block-heading__text">Title for This Block</h2></div>', attributes: {
			uniqueId: 'b72d337', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Title for This Block', textTag: 'h2', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: '41e10e32-c0e9-4b58-92f8-e789a74a7674', name: 'stackable/subtitle', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-subtitle stk-block-subtitle stk-block stk-e7cca4d" data-block-id="e7cca4d"><p class="stk-block-subtitle__text stk-subtitle">Subtitle for This Block</p></div>', attributes: {
			uniqueId: 'e7cca4d', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Subtitle for This Block', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: '8d03884e-2a81-49a0-a930-864be288630b', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-text stk-block-text stk-block stk-1da8f4c" data-block-id="1da8f4c"><p class="stk-block-text__text">Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.</p></div>', attributes: {
			uniqueId: '1da8f4c', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: '3a3b8414-1aa5-4a19-b735-521369646b2b', name: 'stackable/button-group', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button-group stk-block-button-group stk-block stk-e79f4a1" data-block-id="e79f4a1"><div class="stk-row stk-inner-blocks stk-block-content stk-button-group"></div></div>', attributes: {
			uniqueId: 'e79f4a1', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%',
		}, innerBlocks: [ {
			clientId: 'eda8cce0-c056-4cb1-9829-6ed6ba7baa9b', name: 'stackable/button', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button stk-block-button stk-block stk-3ef5604" data-block-id="3ef5604"><a class="stk-link stk-button" href=""><span class="stk-button__inner-text">Button</span></a></div>', attributes: {
				uniqueId: '3ef5604', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, linkHasLink: true, linkNewTab: false, linkHasTitle: true, showBackgroundShape: false, hasP: false, show: true, showText: true, text: 'Button', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		} ],
	} ],
}
