const fs = require( 'fs' )
const path = require( 'path' )
const ImageMinimizerPlugin = require( 'image-minimizer-webpack-plugin' )
const webpack = require( 'webpack' )
require( 'dotenv' ).config()

const posthogToken = process.env.POSTHOG_TOKEN || ''
const posthogHost = process.env.POSTHOG_HOST || 'https://us.i.posthog.com'

// Write PHP constants so activation/deactivation hooks can send events server-side.
fs.writeFileSync(
	path.join( __dirname, '../src/posthog-config.php' ),
	`<?php
// Auto-generated by webpack from .env — do not edit.
if ( ! defined( 'STACKABLE_POSTHOG_TOKEN' ) ) {
	define( 'STACKABLE_POSTHOG_TOKEN', ${ JSON.stringify( posthogToken ) } );
}
if ( ! defined( 'STACKABLE_POSTHOG_HOST' ) ) {
	define( 'STACKABLE_POSTHOG_HOST', ${ JSON.stringify( posthogHost ) } );
}
`
)

module.exports = [
	new webpack.DefinePlugin( {
		'process.env.POSTHOG_TOKEN': JSON.stringify( posthogToken ),
		'process.env.POSTHOG_HOST': JSON.stringify( posthogHost ),
	} ),
	new ImageMinimizerPlugin( {
		minimizerOptions: {
			plugins: [
				[ "pngquant", { quality: [ 0.5, 0.5 ] } ],
			],
		},
	} ),
]
