export default {
	clientId: '43a01831-e3a3-4a52-aa43-fe015966aefa', name: 'stackable/expand', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-expand stk-block-expand stk-block stk-76cbc5c" aria-expanded="false" data-block-id="76cbc5c"><div class="stk-inner-blocks stk-block-content">\n\n\n\n\n\n</div></div>', attributes: {
		uniqueId: '76cbc5c', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [ [ 'aria-expanded', 'false' ] ], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%',
	}, innerBlocks: [ {
		clientId: 'f434ca70-4e42-4025-8f93-588ea5b8e4ef', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-text stk-block-expand__short-text stk-block-text stk-block stk-f06aeac" aria-hidden="false" data-block-id="f06aeac"><p class="stk-block-text__text">Some short text that can be expanded to show more details.</p></div>', attributes: {
			uniqueId: 'f06aeac', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [ [ 'aria-hidden', 'false' ] ], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Some short text that can be expanded to show more details.', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em', className: 'stk-block-expand__short-text',
		}, innerBlocks: [],
	}, {
		clientId: 'cbf380aa-13e1-4644-952d-6212cba50b49', name: 'stackable/button', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button stk-block-button is-style-link stk-block-expand__show-button stk-block stk-8ea90fc" data-block-id="8ea90fc"><a aria-hidden="false" role="button" class="stk-link stk-button" href="#"><span class="stk-button__inner-text">Show more</span></a></div>', attributes: {
			uniqueId: '8ea90fc', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [ [ 'aria-hidden', 'false' ], [ 'role', 'button' ] ], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, linkHasLink: true, linkUrl: '#', linkNewTab: false, linkHasTitle: true, showBackgroundShape: false, hasP: false, show: true, showText: true, text: 'Show more', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em', className: 'is-style-link stk-block-expand__show-button',
		}, innerBlocks: [],
	}, {
		clientId: '94de42d3-cf51-41ca-8dc9-067f22ff7d91', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-text stk-block-expand__more-text stk-block-text stk-block stk-45a5d67" aria-hidden="true" data-block-id="45a5d67"><p class="stk-block-text__text">Some long text that will be expanded when the show more button is clicked by the visitor.</p></div>', attributes: {
			uniqueId: '45a5d67', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [ [ 'aria-hidden', 'true' ] ], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Some long text that will be expanded when the show more button is clicked by the visitor.', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em', className: 'stk-block-expand__more-text',
		}, innerBlocks: [],
	}, {
		clientId: 'f99c547f-5d30-4889-9261-586768656aa5', name: 'stackable/button', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button stk-block-button is-style-link stk-block-expand__hide-button stk-block stk-ff2b0aa" data-block-id="ff2b0aa"><a aria-hidden="true" role="button" class="stk-link stk-button" href="#"><span class="stk-button__inner-text">Show less</span></a></div>', attributes: {
			uniqueId: 'ff2b0aa', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [ [ 'aria-hidden', 'true' ], [ 'role', 'button' ] ], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, linkHasLink: true, linkUrl: '#', linkNewTab: false, linkHasTitle: true, showBackgroundShape: false, hasP: false, show: true, showText: true, text: 'Show less', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em', className: 'is-style-link stk-block-expand__hide-button',
		}, innerBlocks: [],
	} ],
}
