/**
 * External dependencies
 */
import { omit } from 'lodash'
import { i18n } from 'stackable'

/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n'
import { addFilter } from '@wordpress/hooks'

addFilter( 'stackable.team-member.design.apply-block-attributes', 'stackable/team-member', ( attributes, blockAttributes = null ) => {
	return omit( attributes, [
		'image1Id',
		...( blockAttributes && blockAttributes.image1Id ? [ 'image1Url' ] : [] ),
		'image2Id',
		...( blockAttributes && blockAttributes.image2Id ? [ 'image2Url' ] : [] ),
		'image3Id',
		...( blockAttributes && blockAttributes.image3Id ? [ 'image3Url' ] : [] ),
		'image1Alt',
		'image2Alt',
		'image3Alt',
		'name1',
		'name2',
		'name3',
		'position1',
		'position2',
		'position3',
		'description1',
		'description2',
		'description3',
		'social1FacebookUrl',
		'social1TwitterUrl',
		'social1InstagramUrl',
		'social1PinterestUrl',
		'social1LinkedinUrl',
		'social1YoutubeUrl',
		'social1EmailUrl',
		'social2FacebookUrl',
		'social2TwitterUrl',
		'social2InstagramUrl',
		'social2PinterestUrl',
		'social2LinkedinUrl',
		'social2YoutubeUrl',
		'social2EmailUrl',
		'social3FacebookUrl',
		'social3TwitterUrl',
		'social3InstagramUrl',
		'social3PinterestUrl',
		'social3LinkedinUrl',
		'social3YoutubeUrl',
		'social3EmailUrl',
	] )
} )

addFilter( 'stackable.team-member.edit.designs', 'stackable/team-member', designs => {
	return {
		...designs,
		corporateLight1: {
			label: __( 'Corporate Light 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-team-design-corporate-light-01.jpg',
			attributes: {
				borderRadius: 0,
				imageWidth: 150,
				imageHeight: 0,
				imageShapeStretch: false,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-team-corporate-light-01-02.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-team-corporate-light-01-01.jpg',
				nameFontFamily: 'Roboto Condensed',
				nameFontWeight: '100',
				nameLetterSpacing: 0.5,
				nameColor: '#ff550a',
				positionFontFamily: 'Roboto',
				positionFontSize: 18,
				positionColor: '#707070',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#707070',
				socialDesign: 'basic',
				socialTextColor: '#ffffff',
				socialBackgroundColor: '#ffb20b',
				socialHoverEffect: 'lift',
				socialBorderRadius: 100,
				socialTwitterUrl: '#',
				socialLinkedinUrl: '#',
				socialEmailUrl: 'mailto:my@email.com',
				showFacebook: false,
				showInstagram: false,
				showLinkedin: true,
				imageAlign: 'center',
				nameAlign: 'center',
				positionAlign: 'center',
				descriptionAlign: 'center',
				socialAlign: 'center',
				imageBottomMargin: 40,
				descriptionBottomMargin: 55,
				columnGap: 100,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#ffd781',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#ff550a',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#707070',
			},
		},
		corporateLight2: {
			label: __( 'Corporate Light 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-team-design-corporate-light-02.jpg',
			attributes: {
				borderRadius: 0,
				imageWidth: 150,
				imageHeight: 0,
				imageShapeStretch: false,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-team-corporate-light-02-01.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-team-corporate-light-02-02.jpg',
				nameFontFamily: 'Roboto Condensed',
				nameFontWeight: '100',
				nameLetterSpacing: 0.5,
				nameColor: '#1e55d3',
				positionFontFamily: 'Roboto',
				positionFontSize: 18,
				positionColor: '#707070',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#707070',
				socialDesign: 'basic',
				socialTextColor: '#ffffff',
				socialBackgroundColor: '#c49732',
				socialHoverEffect: 'lift',
				socialBorderRadius: 100,
				socialTwitterUrl: '#',
				socialLinkedinUrl: '#',
				socialEmailUrl: 'mailto:my@email.com',
				showFacebook: false,
				showInstagram: false,
				showLinkedin: true,
				imageAlign: 'center',
				nameAlign: 'center',
				positionAlign: 'center',
				descriptionAlign: 'center',
				socialAlign: 'center',
				imageBottomMargin: 40,
				descriptionBottomMargin: 55,
				columnGap: 100,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#6389e0',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#ffffff',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
		corporateDark1: {
			label: __( 'Corporate Dark 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-team-design-corporate-dark-01.jpg',
			attributes: {
				design: 'plain',
				imageWidth: 150,
				imageHeight: 0,
				imageShapeStretch: false,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-team-corporate-dark-01-04.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-team-corporate-dark-01-01.jpg',
				nameFontFamily: 'Roboto Condensed',
				nameFontWeight: '100',
				nameLetterSpacing: 0.5,
				nameColor: '#c5dfb4',
				positionFontFamily: 'Roboto',
				positionFontSize: 18,
				positionColor: '#ffffff',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				socialDesign: 'basic',
				socialTextColor: '#3f4174',
				socialBackgroundColor: '#c4e558',
				socialHoverEffect: 'lift',
				socialBorderRadius: 100,
				socialTwitterUrl: '#',
				socialLinkedinUrl: '#',
				socialEmailUrl: 'mailto:my@email.com',
				showFacebook: false,
				showInstagram: false,
				showLinkedin: true,
				imageAlign: 'center',
				nameAlign: 'center',
				positionAlign: 'center',
				descriptionAlign: 'center',
				socialAlign: 'center',
				imageBottomMargin: 40,
				descriptionBottomMargin: 55,
				paddingTop: 130,
				paddingBottom: 130,
				columnGap: 100,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#0e2448',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#c5dfb4',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
		corporateDark2: {
			label: __( 'Corporate Dark 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-team-design-corporate-dark-02.jpg',
			attributes: {
				borderRadius: 0,
				shadow: 0,
				columnBackgroundColorOpacity: 0,
				imageWidth: 150,
				imageHeight: 0,
				imageShapeStretch: false,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-team-corporate-dark-02-01.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-team-corporate-dark-02-02.jpg',
				nameFontFamily: 'Roboto Condensed',
				nameFontWeight: '100',
				nameLetterSpacing: 0.5,
				nameColor: '#06c19d',
				positionFontFamily: 'Roboto',
				positionFontSize: 18,
				positionColor: '#ffffff',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				socialDesign: 'basic',
				socialTextColor: '#393939',
				socialBackgroundColor: '#06c19d',
				socialHoverEffect: 'lift',
				socialBorderRadius: 100,
				socialTwitterUrl: '#',
				socialLinkedinUrl: '#',
				socialEmailUrl: 'mailto:my@email.com',
				showFacebook: false,
				showInstagram: false,
				showLinkedin: true,
				imageAlign: 'center',
				nameAlign: 'center',
				positionAlign: 'center',
				descriptionAlign: 'center',
				socialAlign: 'center',
				imageBottomMargin: 40,
				descriptionBottomMargin: 55,
				columnGap: 100,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColorType: 'gradient',
				blockBackgroundBackgroundColor: '#717171',
				blockBackgroundBackgroundColor2: '#393939',
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#06c19d',
				showBlockDescription: true,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#ffffff',
			},
		},
	}
} )
