export default {
	clientId: '227fd332-1447-4b05-b5ca-06fd0541c8da', name: 'stackable/video-popup', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-video-popup stk-block-video-popup stk-block stk-436a2b2" data-video="" data-block-id="436a2b2"><button class="stk-block-video-popup__overlay stk-row stk-inner-blocks stk-block-content stk-hover-parent" aria-label="Play Video">\n\n</button></div>', attributes: {
		uniqueId: '436a2b2', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%',
	}, innerBlocks: [ {
		clientId: '7c35a30c-63e1-4da3-8cb6-647c14f4db39', name: 'stackable/icon', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-icon stk-block-icon has-text-align-center stk-block stk-4e1adcf" data-block-id="4e1adcf"><span class="stk--svg-wrapper"><div class="stk--inner-svg"><svg style="height:0;width:0"><defs><linearGradient id="linear-gradient-4e1adcf" x1="0" x2="100%" y1="0" y2="0"><stop offset="0%" style="stop-opacity:1;stop-color:var(--linear-gradient-4-e-1-adcf-color-1)"></stop><stop offset="100%" style="stop-opacity:1;stop-color:var(--linear-gradient-4-e-1-adcf-color-2)"></stop></linearGradient></defs></svg><svg data-prefix="fas" data-icon="play" class="svg-inline--fa fa-play fa-w-14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" aria-hidden="true" width="32" height="32"><path fill="currentColor" d="M424.4 214.7L72.4 6.6C43.8-10.3 0 6.1 0 47.9V464c0 37.5 40.7 60.1 72.4 41.3l352-208c31.4-18.5 31.5-64.1 0-82.6z"></path></svg></div></span></div>', attributes: {
			uniqueId: '4e1adcf', hasBackground: false, hasBorders: false, contentAlign: 'center', effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, icon: '<svg data-prefix="fas" data-icon="play" class="svg-inline--fa fa-play fa-w-14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" aria-hidden="true"><path fill="currentColor" d="M424.4 214.7L72.4 6.6C43.8-10.3 0 6.1 0 47.9V464c0 37.5 40.7 60.1 72.4 41.3l352-208c31.4-18.5 31.5-64.1 0-82.6z"></path></svg>', showBackgroundShape: false, linkHasLink: false, linkNewTab: false, linkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', iconColor1: '#FFFFFF',
		}, innerBlocks: [],
	}, {
		clientId: '6044c2c8-8c50-409d-92da-cbaf633c69c6', name: 'stackable/image', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-image stk-block-image stk-block stk-d4394aa" data-block-id="d4394aa"><figure class="stk-img-wrapper stk-image--shape-stretch"><img class="stk-img" src="https://source.unsplash.com/800x500/?sea,coast,water" width="150" height="300"/></figure></div>', attributes: {
			uniqueId: 'd4394aa', hasBackground: false, hasBorders: false, imageShow: true, imageUrl: 'https://source.unsplash.com/800x500/?sea,coast,water', imageSize: 'full', imageShapeStretch: true, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', imageWidthUnit: '%', imageWidthUnitTablet: '%', imageWidthUnitMobile: '%',
		}, innerBlocks: [],
	} ],
}
