export default {
	attributes: {
		playButtonType: 'normal',
		previewBackgroundColor: '#000000',
		previewBackgroundMediaUrl: 'http://sandbox.gambit.ph/bea/wp-content/uploads/sites/59/2020/09/mike-swigunski-tYGZvg-Ozh4-unsplash.jpg',
		previewBackgroundCustomSizeUnit: '%',
		previewTabletBackgroundCustomSizeUnit: '%',
		previewMobileBackgroundCustomSizeUnit: '%',
		uniqueClass: 'ugb-ee3d6d0',
		hideDesktop: false,
		hideTablet: false,
		hideMobile: false,
		showBlockBackground: false,
		blockBackgroundBackgroundCustomSizeUnit: '%',
		blockBackgroundTabletBackgroundCustomSizeUnit: '%',
		blockBackgroundMobileBackgroundCustomSizeUnit: '%',
		topSeparatorDesign: 'wave-1',
		bottomSeparatorDesign: 'wave-1',
		topSeparatorShadow: true,
		bottomSeparatorShadow: true,
		showBlockTitle: false,
		blockTitleLineHeightUnit: 'em',
		blockTitleTabletLineHeightUnit: 'em',
		blockTitleMobileLineHeightUnit: 'em',
		showBlockDescription: false,
		blockDescriptionLineHeightUnit: 'em',
		blockDescriptionTabletLineHeightUnit: 'em',
		blockDescriptionMobileLineHeightUnit: 'em',
	},
}
