<?php
/**
 * PostHog analytics — activation, first content, published-page milestones.
 *
 * @package Stackable
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Build-time config (generated by webpack from .env). Falls back to empty.
if ( file_exists( __DIR__ . '/posthog-config.php' ) ) {
	require_once __DIR__ . '/posthog-config.php';
}
if ( ! defined( 'STACKABLE_POSTHOG_TOKEN' ) ) {
	define( 'STACKABLE_POSTHOG_TOKEN', '' );
}
if ( ! defined( 'STACKABLE_POSTHOG_HOST' ) ) {
	define( 'STACKABLE_POSTHOG_HOST', 'https://us.i.posthog.com' );
}

/** Option: opaque install UUID used as PostHog distinct_id (avoids localhost collisions). */
define( 'STACKABLE_POSTHOG_INSTALL_ID', 'stackable_posthog_install_id' );
/** Option: post IDs that are published and contain Stackable blocks. */
define( 'STACKABLE_POSTHOG_PUBLISHED_IDS', 'stackable_posthog_published_stackable_posts' );
/** Option: last published-page milestone that was fired. */
define( 'STACKABLE_POSTHOG_PUBLISHED_MILESTONE', 'stackable_posthog_published_milestone' );
/** Option: whether first_stackable_content was already recorded server-side. */
define( 'STACKABLE_POSTHOG_FIRST_CONTENT', 'stackable_posthog_first_content' );
/** Option: whether Design Library insert was recorded (for person props). */
define( 'STACKABLE_POSTHOG_HAS_DESIGN_LIBRARY', 'stackable_posthog_has_design_library' );
/** Option: one-time backfill of published Stackable pages (no historical events). */
define( 'STACKABLE_POSTHOG_PUBLISHED_SCANNED', 'stackable_posthog_published_scanned' );

if ( ! function_exists( 'stackable_posthog_content_has_stackable' ) ) {
	/**
	 * Whether post content contains a Stackable v3 block.
	 *
	 * @param string $content Post content.
	 * @return bool
	 */
	function stackable_posthog_content_has_stackable( $content ) {
		return is_string( $content ) && false !== strpos( $content, '<!-- wp:stackable/' );
	}
}

if ( ! function_exists( 'stackable_posthog_publish_milestones' ) ) {
	/**
	 * Milestone thresholds for published Stackable pages: 1, then every 5.
	 *
	 * @param int $up_to Include milestones up to this count.
	 * @return int[]
	 */
	function stackable_posthog_publish_milestones( $up_to ) {
		$milestones = array( 1 );
		for ( $i = 5; $i <= max( (int) $up_to, 5 ); $i += 5 ) {
			$milestones[] = $i;
		}
		return $milestones;
	}
}

if ( ! function_exists( 'stackable_posthog_queue_activation_events' ) ) {
	/**
	 * Queue activation events for the next JS page load.
	 */
	function stackable_posthog_queue_activation_events() {
		// Ensure install UUID exists before any events fire.
		stackable_posthog_install_id();

		$events = array( 'plugin_activated' );

		if ( defined( 'STACKABLE_BUILD' ) && STACKABLE_BUILD === 'premium' ) {
			$events[] = 'premium_plugin_activated';
		}

		update_option( 'stackable_posthog_pending_events', $events, false );
	}
	register_activation_hook( STACKABLE_FILE, 'stackable_posthog_queue_activation_events' );
}

if ( ! function_exists( 'stackable_posthog_install_id' ) ) {
	/**
	 * Opaque per-install distinct ID (UUID stored in options).
	 * Survives Site Address changes and avoids localhost collisions across machines.
	 *
	 * @return string
	 */
	function stackable_posthog_install_id() {
		$id = get_option( STACKABLE_POSTHOG_INSTALL_ID, '' );
		if ( is_string( $id ) && '' !== $id ) {
			return $id;
		}

		$id = wp_generate_uuid4();
		update_option( STACKABLE_POSTHOG_INSTALL_ID, $id, false );
		return $id;
	}
}

if ( ! function_exists( 'stackable_posthog_site_address' ) ) {
	/**
	 * Normalized WP Site Address (URL) for metadata only — not used as distinct_id.
	 *
	 * @return string
	 */
	function stackable_posthog_site_address() {
		$home = home_url( '/' );
		$home = untrailingslashit( $home );
		$parts = wp_parse_url( $home );
		if ( empty( $parts['host'] ) ) {
			return $home ? $home : '';
		}
		$scheme = isset( $parts['scheme'] ) ? strtolower( $parts['scheme'] ) : 'https';
		$host = strtolower( $parts['host'] );
		$path = isset( $parts['path'] ) ? untrailingslashit( $parts['path'] ) : '';
		$port = isset( $parts['port'] ) ? ':' . (int) $parts['port'] : '';
		return $scheme . '://' . $host . $port . $path;
	}
}

if ( ! function_exists( 'stackable_posthog_person_props' ) ) {
	/**
	 * Current person properties for Stackable analytics context (site-level).
	 *
	 * @return array
	 */
	function stackable_posthog_person_props() {
		$ids = get_option( STACKABLE_POSTHOG_PUBLISHED_IDS, array() );
		if ( ! is_array( $ids ) ) {
			$ids = array();
		}
		$count = count( $ids );

		return array(
			'install_id' => stackable_posthog_install_id(),
			'site_address' => stackable_posthog_site_address(),
			'build' => defined( 'STACKABLE_BUILD' ) ? STACKABLE_BUILD : 'free',
			'stackable_published_pages' => $count,
			'stackable_published_milestone' => (int) get_option( STACKABLE_POSTHOG_PUBLISHED_MILESTONE, 0 ),
			'has_first_stackable_content' => (bool) get_option( STACKABLE_POSTHOG_FIRST_CONTENT, false ),
			'has_design_library_insert' => (bool) get_option( STACKABLE_POSTHOG_HAS_DESIGN_LIBRARY, false ),
		);
	}
}

if ( ! function_exists( 'stackable_posthog_capture' ) ) {
	/**
	 * Send a single event to PostHog via the Capture API.
	 *
	 * @param string $event      Event name.
	 * @param array  $properties Optional event properties (may include $set / $set_once).
	 */
	function stackable_posthog_capture( $event, $properties = array() ) {
		if ( empty( STACKABLE_POSTHOG_TOKEN ) ) {
			return;
		}

		$distinct_id = stackable_posthog_install_id();

		$set = isset( $properties['$set'] ) && is_array( $properties['$set'] ) ? $properties['$set'] : array();
		$set_once = isset( $properties['$set_once'] ) && is_array( $properties['$set_once'] ) ? $properties['$set_once'] : array();
		unset( $properties['$set'], $properties['$set_once'] );

		$person = stackable_posthog_person_props();
		$properties = array_merge( array(
			'$lib' => 'stackable-php',
			'build' => $person['build'],
			'version' => defined( 'STACKABLE_VERSION' ) ? STACKABLE_VERSION : '',
			'install_id' => $person['install_id'],
			'site_address' => $person['site_address'],
			'stackable_published_pages' => $person['stackable_published_pages'],
		), $properties );

		$properties['$set'] = array_merge( $person, $set );
		if ( ! empty( $set_once ) ) {
			$properties['$set_once'] = $set_once;
		}

		$payload = array(
			'api_key' => STACKABLE_POSTHOG_TOKEN,
			'event' => $event,
			'distinct_id' => $distinct_id,
			'properties' => $properties,
		);

		wp_remote_post(
			trailingslashit( STACKABLE_POSTHOG_HOST ) . 'capture/',
			array(
				'timeout' => 2,
				'blocking' => false,
				'headers' => array( 'Content-Type' => 'application/json' ),
				'body' => wp_json_encode( $payload ),
			)
		);
	}
}

if ( ! function_exists( 'stackable_posthog_on_deactivation' ) ) {
	/**
	 * Send plugin_deactivated when Stackable is deactivated.
	 */
	function stackable_posthog_on_deactivation() {
		stackable_posthog_capture( 'plugin_deactivated' );
	}
	register_deactivation_hook( STACKABLE_FILE, 'stackable_posthog_on_deactivation' );
}

if ( ! function_exists( 'stackable_posthog_maybe_fire_publish_milestones' ) ) {
	/**
	 * Fire stackable_page_published for each newly crossed milestone.
	 *
	 * @param int $count Current published Stackable page count.
	 */
	function stackable_posthog_maybe_fire_publish_milestones( $count ) {
		$count = (int) $count;
		$last = (int) get_option( STACKABLE_POSTHOG_PUBLISHED_MILESTONE, 0 );
		$crossed = array();

		foreach ( stackable_posthog_publish_milestones( $count ) as $milestone ) {
			if ( $milestone > $last && $milestone <= $count ) {
				$crossed[] = $milestone;
			}
		}

		if ( empty( $crossed ) ) {
			return;
		}

		foreach ( $crossed as $milestone ) {
			stackable_posthog_capture( 'stackable_page_published', array(
				'milestone' => $milestone,
				'stackable_published_pages' => $count,
				'$set' => array(
					'stackable_published_pages' => $count,
					'stackable_published_milestone' => $milestone,
				),
			) );
			$last = $milestone;
		}

		update_option( STACKABLE_POSTHOG_PUBLISHED_MILESTONE, $last, false );
	}
}

if ( ! function_exists( 'stackable_posthog_sync_published_post' ) ) {
	/**
	 * Add/remove a post from the published-Stackable set and fire milestones.
	 *
	 * @param int     $post_id Post ID.
	 * @param WP_Post $post    Post object.
	 */
	function stackable_posthog_sync_published_post( $post_id, $post ) {
		if ( wp_is_post_revision( $post_id ) || wp_is_post_autosave( $post_id ) ) {
			return;
		}

		if ( ! $post instanceof WP_Post ) {
			$post = get_post( $post_id );
		}
		if ( ! $post || 'nav_menu_item' === $post->post_type ) {
			return;
		}

		// Public content types only (posts, pages, and public CPTs).
		$post_type_object = get_post_type_object( $post->post_type );
		if ( ! $post_type_object || empty( $post_type_object->public ) ) {
			return;
		}

		$ids = get_option( STACKABLE_POSTHOG_PUBLISHED_IDS, array() );
		if ( ! is_array( $ids ) ) {
			$ids = array();
		}
		$ids = array_map( 'intval', $ids );
		$was_in_list = in_array( (int) $post_id, $ids, true );
		$qualifies = ( 'publish' === $post->post_status ) && stackable_posthog_content_has_stackable( $post->post_content );

		if ( $qualifies && ! $was_in_list ) {
			$ids[] = (int) $post_id;
			$ids = array_values( array_unique( $ids ) );
			update_option( STACKABLE_POSTHOG_PUBLISHED_IDS, $ids, false );

			if ( ! get_option( STACKABLE_POSTHOG_FIRST_CONTENT, false ) ) {
				update_option( STACKABLE_POSTHOG_FIRST_CONTENT, 1, false );
				stackable_posthog_capture( 'first_stackable_content', array(
					'source' => 'publish',
					'$set' => array( 'has_first_stackable_content' => true ),
					'$set_once' => array( 'first_stackable_content_source' => 'publish' ),
				) );
			}

			stackable_posthog_maybe_fire_publish_milestones( count( $ids ) );
		} elseif ( ! $qualifies && $was_in_list ) {
			$ids = array_values( array_diff( $ids, array( (int) $post_id ) ) );
			update_option( STACKABLE_POSTHOG_PUBLISHED_IDS, $ids, false );
			// Do not fire milestones on decrease; person prop updates on next event.
		}
	}
	add_action( 'save_post', 'stackable_posthog_sync_published_post', 20, 2 );
}

if ( ! function_exists( 'stackable_posthog_on_before_delete_post' ) ) {
	/**
	 * Remove deleted posts from the published-Stackable set.
	 *
	 * @param int $post_id Post ID.
	 */
	function stackable_posthog_on_before_delete_post( $post_id ) {
		$ids = get_option( STACKABLE_POSTHOG_PUBLISHED_IDS, array() );
		if ( ! is_array( $ids ) || ! in_array( (int) $post_id, array_map( 'intval', $ids ), true ) ) {
			return;
		}
		$ids = array_values( array_diff( array_map( 'intval', $ids ), array( (int) $post_id ) ) );
		update_option( STACKABLE_POSTHOG_PUBLISHED_IDS, $ids, false );
	}
	add_action( 'before_delete_post', 'stackable_posthog_on_before_delete_post' );
}

if ( ! function_exists( 'stackable_posthog_backfill_published_pages' ) ) {
	/**
	 * One-time scan: seed published-page count without firing historical milestones.
	 */
	function stackable_posthog_backfill_published_pages() {
		if ( get_option( STACKABLE_POSTHOG_PUBLISHED_SCANNED ) ) {
			return;
		}
		if ( ! is_admin() || ! current_user_can( 'edit_posts' ) ) {
			return;
		}

		$query = new WP_Query( array(
			'post_type' => array_values( get_post_types( array( 'public' => true ) ) ),
			'post_status' => 'publish',
			'posts_per_page' => 500,
			'fields' => 'ids',
			'no_found_rows' => true,
			'update_post_meta_cache' => false,
			'update_post_term_cache' => false,
		) );

		$ids = array();
		foreach ( $query->posts as $post_id ) {
			$post = get_post( $post_id );
			if ( ! $post ) {
				continue;
			}
			if ( stackable_posthog_content_has_stackable( $post->post_content ) ) {
				$ids[] = (int) $post_id;
			}
		}

		$ids = array_values( array_unique( $ids ) );
		$count = count( $ids );
		update_option( STACKABLE_POSTHOG_PUBLISHED_IDS, $ids, false );

		// Set last milestone without capturing historical events.
		$last = 0;
		foreach ( stackable_posthog_publish_milestones( $count ) as $milestone ) {
			if ( $milestone <= $count ) {
				$last = $milestone;
			}
		}
		update_option( STACKABLE_POSTHOG_PUBLISHED_MILESTONE, $last, false );
		update_option( STACKABLE_POSTHOG_PUBLISHED_SCANNED, 1, false );

		if ( $count > 0 && ! get_option( STACKABLE_POSTHOG_FIRST_CONTENT, false ) ) {
			update_option( STACKABLE_POSTHOG_FIRST_CONTENT, 1, false );
		}
	}
	add_action( 'admin_init', 'stackable_posthog_backfill_published_pages', 20 );
}

if ( ! function_exists( 'stackable_posthog_mark_first_content_from_js' ) ) {
	/**
	 * AJAX: persist first-content / design-library flags set from the editor.
	 */
	function stackable_posthog_mark_first_content_from_js() {
		check_ajax_referer( 'stackable', 'nonce' );
		if ( ! current_user_can( 'edit_posts' ) ) {
			wp_send_json_error( null, 403 );
		}

		$flag = isset( $_POST['flag'] ) ? sanitize_key( wp_unslash( $_POST['flag'] ) ) : '';
		if ( 'first_content' === $flag ) {
			update_option( STACKABLE_POSTHOG_FIRST_CONTENT, 1, false );
		} elseif ( 'design_library' === $flag ) {
			update_option( STACKABLE_POSTHOG_HAS_DESIGN_LIBRARY, 1, false );
			update_option( STACKABLE_POSTHOG_FIRST_CONTENT, 1, false );
		}

		wp_send_json_success();
	}
	add_action( 'wp_ajax_stackable_posthog_flag', 'stackable_posthog_mark_first_content_from_js' );
}

if ( ! function_exists( 'stackable_posthog_localize_context' ) ) {
	/**
	 * Expose pending events + analytics context to JS.
	 *
	 * @param array $args Localized script args.
	 * @return array
	 */
	function stackable_posthog_localize_context( $args ) {
		static $pending = null;

		if ( null === $pending ) {
			$pending = get_option( 'stackable_posthog_pending_events', array() );
			if ( ! empty( $pending ) && is_array( $pending ) ) {
				delete_option( 'stackable_posthog_pending_events' );
			} else {
				$pending = array();
			}
		}

		if ( ! empty( $pending ) ) {
			$args['posthogPendingEvents'] = array_values( $pending );
		}

		$person = stackable_posthog_person_props();
		$args['posthogContext'] = array(
			'installId' => $person['install_id'],
			'siteAddress' => $person['site_address'],
			'build' => $person['build'],
			'version' => defined( 'STACKABLE_VERSION' ) ? STACKABLE_VERSION : '',
			'publishedPages' => $person['stackable_published_pages'],
			'publishedMilestone' => $person['stackable_published_milestone'],
			'hasFirstContent' => $person['has_first_stackable_content'],
			'hasDesignLibraryInsert' => $person['has_design_library_insert'],
		);

		return $args;
	}
	add_filter( 'stackable_localize_script', 'stackable_posthog_localize_context' );
	add_filter( 'stackable_localize_settings_script', 'stackable_posthog_localize_context' );
}
