export default {
	restrictContentWidth: false,
	design: 'basic',
	height: 'normal',
	columnBackgroundCustomSizeUnit: '%',
	columnTabletBackgroundCustomSizeUnit: '%',
	columnMobileBackgroundCustomSizeUnit: '%',
	imageSize: 'full',
	imageWidthUnit: '%',
	imageTabletWidthUnit: '%',
	imageMobileWidthUnit: '%',
	imageCollapseOnMobile: true,
	imageCollapseOnMobileHeight: 300,
	hideDesktop: false,
	hideTablet: false,
	hideMobile: false,
	showBlockBackground: false,
	blockBackgroundBackgroundCustomSizeUnit: '%',
	blockBackgroundTabletBackgroundCustomSizeUnit: '%',
	blockBackgroundMobileBackgroundCustomSizeUnit: '%',
	topSeparatorDesign: 'wave-1',
	bottomSeparatorDesign: 'wave-1',
	topSeparatorShadow: true,
	bottomSeparatorShadow: true,
}
