name: Compressed Size

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4 # Checkout the Stackable Premium repo.
      with:
        repository: 'bfintal/Stackable-Premium'
        ref: 'v3'
        path: 'pro__premium_only'
        token: '${{ secrets.ACCESS_KEY }}'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install Dependencies
      run: |
        npm install
        cd pro__premium_only && npm install
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        clean-script: "clean"
        pattern: "./build/stackable/**"
        exclude: "{**/*.map,**/node_modules/**}"
