name: Compressed Size

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2 # Checkout the Stackable Premium repo.
      with:
        repository: 'bfintal/Stackable-Premium'
        ref: 'v3'
        path: 'pro__premium_only'
        token: '${{ secrets.ACCESS_KEY }}'
    - name: Install Composer Dependencies
      run: |
        composer install --prefer-dist --no-progress --ignore-platform-reqs
    - name: Setup Node # Fix because we can't do npm ci --legacy-peer-deps
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        clean-script: "clean"
        pattern: "./build/stackable/**"
        exclude: "{**/*.map,**/node_modules/**}"
