name: Compressed Size

on:
  pull_request:
    branches: [ v3 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        clean-script: "clean"
        pattern: "./build/**/*.{js,css,php}"
        exclude: "{**/*.map,**/node_modules/**}"
