name: Plugin Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Build Stackable Free Plugin
      run: |
        npm ci
        npm run build:no-translate

    - name: Change build version
      run: |
        node ./tools/append-build-version.js ${GITHUB_REF_NAME//\//-}
        mv build/stackable build/stackable-${GITHUB_REF_NAME//\//-}

    - uses: actions/upload-artifact@v3
      with:
        name: plugin
        path: build/stackable-${GITHUB_REF_NAME//\//-}
