name: Plugin Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Set the version suffix for the output
      run: echo VERSION_SUFFIX=${GITHUB_REF_NAME//\//-} >> $GITHUB_ENV

    - name: Build Stackable Free Plugin
      run: |
        npm ci
        npm run build:no-translate

    - name: Change build version
      run: |
        node ./tools/append-build-version.js $VERSION_SUFFIX
        mv build/stackable build/stackable-$VERSION_SUFFIX

    - name: Create plugin zip file artifact
      uses: actions/upload-artifact@v3
      with:
        name: stackable-${{ env.VERSION_SUFFIX }}
        path: build/stackable-*

    - name: Add artifact links to pull request
      uses: tonyhallett/artifacts-url-comments@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prefix: "PR Build: "
        suffix: "This build contains changes from this pull request"
        format: "name"
        addTo: "pull"
