export default {
	clientId: 'e87e0c98-7df2-4118-a62a-6d91b031bff8', name: 'stackable/hero', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-hero stk-block-hero stk-block stk-c5a87cb" data-block-id="c5a87cb"><style>.stk-c5a87cb-container{background-color:#000000 !important}.stk-c5a87cb-container:before{background-color:#000000 !important}.stk-c5a87cb .stk-block-hero__content{min-height:500px !important;justify-content:center !important;display:flex !important;flex-direction:column !important}</style><div class="stk-block-content stk-inner-blocks has-text-align-center stk-block-hero__content stk-content-align stk-container stk-c5a87cb-container stk-hover-parent">\n\n\n\n</div></div>', attributes: {
		uniqueId: 'c5a87cb', hasBackground: false, hasBorders: false, hasContainer: true, containerBackgroundColor: '#000000', containerHeight: 500, containerVerticalAlign: 'center', contentAlign: 'center', effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], displayCondition: {}, hideDesktop: false, hideTablet: false, hideMobile: false, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', containerBackgroundCustomSizeUnit: '%', containerBackgroundCustomSizeUnitTablet: '%', containerBackgroundCustomSizeUnitMobile: '%',
	}, innerBlocks: [ {
		clientId: 'ee26250b-a9ea-48f3-9446-20ce2c76e4fd', name: 'stackable/heading', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-heading stk-block-heading stk-block stk-ab8669f" data-block-id="ab8669f"><style>.stk-ab8669f .stk-block-heading__text{color:#FFFFFF !important}</style><h2 class="stk-block-heading__text has-text-color has-white-color">Header Title</h2></div>', attributes: {
			uniqueId: 'ab8669f', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, textColorClass: 'has-white-color', textColor1: '#FFFFFF', hasP: false, show: true, showText: true, text: 'Header Title', textTag: 'h2', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: 'f5a51c5a-f826-4bfc-820d-62f17ebc0d0f', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-text stk-block-text stk-block stk-49b0171" data-block-id="49b0171"><style>.stk-49b0171 .stk-block-text__text{color:#FFFFFF !important}</style><p class="stk-block-text__text has-text-color has-white-color">Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.</p></div>', attributes: {
			uniqueId: '49b0171', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, textColorClass: 'has-white-color', textColor1: '#FFFFFF', hasP: false, show: true, showText: true, text: 'Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
		}, innerBlocks: [],
	}, {
		clientId: '8d40d102-6f47-44cd-a88b-317984f71a55', name: 'stackable/button-group', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button-group stk-block-button-group stk-block stk-869a544" data-block-id="869a544"><div class="stk-row stk-inner-blocks stk-block-content stk-button-group"></div></div>', attributes: {
			uniqueId: '869a544', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%',
		}, innerBlocks: [ {
			clientId: '0881ca43-cd88-4bb4-9ad3-30088b36aa4a', name: 'stackable/button', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button stk-block-button stk-block stk-12e2b68" data-block-id="12e2b68"><a class="stk-link stk-button" href=""><span class="stk-button__inner-text">Button</span></a></div>', attributes: {
				uniqueId: '12e2b68', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, linkHasLink: true, linkNewTab: false, linkHasTitle: true, showBackgroundShape: false, hasP: false, show: true, showText: true, text: 'Button', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		} ],
	} ],
}
