/**
 * External dependencies
 */
import { omit } from 'lodash'
import { i18n } from 'stackable'

/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n'
import { addFilter } from '@wordpress/hooks'

// Remove text from block designs being applied.
addFilter( 'stackable.feature-grid.design.no-text-attributes', 'stackable/feature-grid', attributes => {
	return omit( attributes, [
		'title1',
		'title2',
		'title3',
		'title4',
		'description1',
		'description2',
		'description3',
		'description4',
		'button1Text',
		'button2Text',
		'button3Text',
		'button4Text',
	] )
} )

// Ignore these attributes when exporting / applying designs.
addFilter( 'stackable.feature-grid.design.filtered-block-attributes', 'stackable/feature-grid', ( attributes, blockAttributes = null ) => {
	return omit( attributes, [
		'image1Id',
		...( blockAttributes && blockAttributes.image1Id ? [ 'image1Url' ] : [] ),
		'image2Id',
		...( blockAttributes && blockAttributes.image2Id ? [ 'image2Url' ] : [] ),
		'image3Id',
		...( blockAttributes && blockAttributes.image3Id ? [ 'image3Url' ] : [] ),
		'image4Id',
		...( blockAttributes && blockAttributes.image4Id ? [ 'image4Url' ] : [] ),
		'button1Url',
		'button1NewTab',
		'button1NoFollow',
		'button2Url',
		'button2NewTab',
		'button2NoFollow',
		'button3Url',
		'button3NewTab',
		'button3NoFollow',
		'button4Url',
		'button4NewTab',
		'button4NoFollow',
	] )
} )

addFilter( 'stackable.feature-grid.edit.designs', 'stackable/feature-grid', designs => {
	return {
		...designs,
		corporateLight1: {
			label: __( 'Corporate Light 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-featuregrid-design-corporate-light-01.jpg',
			attributes: {
				borderRadius: 0,
				columnBackgroundColor: '#ffffff',
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-light-01-03.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-light-01-02.jpg',
				image3Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-light-01-01.jpg',
				image1Alt: 'Title',
				image2Alt: 'Title',
				image3Alt: 'Title',
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleFontSize: 34,
				titleColor: '#ff550a',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#707070',
				buttonFontFamily: 'Roboto Condensed',
				buttonLetterSpacing: 0.5,
				buttonDesign: 'basic',
				buttonSize: 'small',
				buttonTextColor: '#ffffff',
				buttonBackgroundColor: '#ffb20b',
				buttonHoverEffect: 'lift',
				buttonBorderRadius: 100,
				imageBottomMargin: 40,
				descriptionBottomMargin: 40,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#ffd781',
				showTopSeparator: false,
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#ff550a',
				showBlockDescription: true,
				blockDescriptionBottomMargin: 50,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#707070',
				contentAlign: 'left',
			},
		},
		corporateLight2: {
			label: __( 'Corporate Light 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-featuregrid-design-corporate-light-02.jpg',
			attributes: {
				borderRadius: 0,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-light-02-01.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-light-02-02.jpg',
				image3Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-light-02-03.jpg',
				image1Alt: 'Title',
				image2Alt: 'Title',
				image3Alt: 'Title',
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleFontSize: 34,
				titleColor: '#1e55d3',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#707070',
				buttonFontFamily: 'Roboto Condensed',
				buttonLetterSpacing: 0.5,
				buttonDesign: 'basic',
				buttonSize: 'small',
				buttonTextColor: '#ffffff',
				buttonBackgroundColor: '#c49732',
				buttonHoverEffect: 'lift',
				buttonBorderRadius: 100,
				imageBottomMargin: 40,
				descriptionBottomMargin: 40,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#ffffff',
				showTopSeparator: false,
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#c49732',
				showBlockDescription: true,
				blockDescriptionBottomMargin: 50,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				blockDescriptionColor: '#707070',
				contentAlign: 'left',
			},
		},
		corporateDark1: {
			label: __( 'Corporate Dark 1', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-featuregrid-design-corporate-dark-01.jpg',
			attributes: {
				borderRadius: 0,
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-dark-01-01.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-dark-01-02.jpg',
				image3Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-dark-01-03.jpg',
				image1Alt: 'Title',
				image2Alt: 'Title',
				image3Alt: 'Title',
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleFontSize: 34,
				titleColor: '#1785cb',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#707070',
				buttonFontFamily: 'Roboto Condensed',
				buttonLetterSpacing: 0.5,
				buttonDesign: 'basic',
				buttonSize: 'small',
				buttonTextColor: '#ffffff',
				buttonBackgroundColor: '#c4e558',
				buttonHoverEffect: 'lift',
				buttonBorderRadius: 100,
				imageBottomMargin: 40,
				descriptionBottomMargin: 40,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#0e2448',
				showTopSeparator: false,
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#eeffb5',
				showBlockDescription: true,
				blockDescriptionBottomMargin: 50,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				contentAlign: 'left',
			},
		},
		corporateDark2: {
			label: __( 'Corporate Dark 2', i18n ),
			image: 'https://gambitph.github.io/Stackable/assets/block-design-previews/stack-featuregrid-design-corporate-dark-02.jpg',
			attributes: {
				borderRadius: 0,
				columnBackgroundColor: '#2f2f2f',
				image1Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-dark-02-04.jpg',
				image2Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-dark-02-02.jpg',
				image3Url: 'https://gambitph.github.io/Stackable/assets/block-design-assets/stack-feature-grid-corporate-dark-02-01.jpg',
				image1Alt: 'Title',
				image2Alt: 'Title',
				image3Alt: 'Title',
				titleFontFamily: 'Roboto Condensed',
				titleFontWeight: '100',
				titleLetterSpacing: 0.5,
				titleFontSize: 34,
				titleColor: '#06c19d',
				descriptionFontFamily: 'Serif',
				descriptionColor: '#ffffff',
				buttonFontFamily: 'Roboto Condensed',
				buttonLetterSpacing: 0.5,
				buttonDesign: 'basic',
				buttonSize: 'small',
				buttonTextColor: '#ffffff',
				buttonBackgroundColor: '#06c19d',
				buttonHoverEffect: 'lift',
				buttonBorderRadius: 100,
				imageBottomMargin: 40,
				descriptionBottomMargin: 40,
				showBlockBackground: true,
				blockInnerWidth: 'wide',
				align: 'full',
				blockBackgroundBackgroundColor: '#717171',
				showTopSeparator: false,
				showBlockTitle: true,
				blockTitleFontFamily: 'Roboto Condensed',
				blockTitleFontWeight: '100',
				blockTitleLetterSpacing: 0.5,
				blockTitleAlign: 'center',
				blockTitleColor: '#06c19d',
				showBlockDescription: true,
				blockDescriptionBottomMargin: 50,
				blockDescriptionFontFamily: 'Serif',
				blockDescriptionAlign: 'center',
				contentAlign: 'left',
			},
		},
	}
} )
