export default {
	clientId: 'c560b5cd-d72b-43f3-b184-f33b84348ad0', name: 'stackable/feature-grid', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-feature-grid alignfull is-style-default stk-block-feature-grid stk-block stk-150ccfb" data-block-id="150ccfb"><div class="stk-row stk-inner-blocks has-text-align-center stk-block-content stk-content-align alignwide">\n\n</div></div>', attributes: {
		uniqueId: '150ccfb', hasBackground: false, hasBorders: false, contentAlign: 'center', effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, innerBlockContentAlign: 'alignwide', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', align: 'full', className: 'is-style-default',
	}, innerBlocks: [ {
		clientId: 'baa2ade6-89ce-4562-8a91-d9910d5c8d22', name: 'stackable/column', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-column stk-block-column stk-column stk-block stk-b195383" data-block-id="b195383"><div class="stk-block-content stk-inner-blocks stk-column-wrapper stk-block-column__content stk-container stk-b195383-container stk-hover-parent">\n\n\n\n\n\n</div></div>', attributes: {
			uniqueId: 'b195383', hasBackground: false, hasBorders: false, hasContainer: true, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', containerBackgroundCustomSizeUnit: '%', containerBackgroundCustomSizeUnitTablet: '%', containerBackgroundCustomSizeUnitMobile: '%',
		}, innerBlocks: [ {
			clientId: '92c366c9-3034-4e99-b76c-9b7adbd0efc2', name: 'stackable/image', isValid: true, validationIssues: [], originalContent: "<div class=\"wp-block-stackable-image stk-block-image stk-block stk-9fbcacb\" data-block-id=\"9fbcacb\"><style>.stk-9fbcacb .stk-img-wrapper{width:75px !important;height:75px !important}.stk-9fbcacb .stk-img-wrapper img{mask-image:url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCI+PC9jaXJjbGU+PC9zdmc+') !important;-webkit-mask-image:url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCI+PC9jaXJjbGU+PC9zdmc+') !important}</style><figure class=\"stk-img-wrapper stk-img--shape\"><img class=\"stk-img\" src=\"https://source.unsplash.com/400x300/?donut\" width=\"300\" height=\"300\"/></figure></div>", attributes: {
				uniqueId: '9fbcacb', hasBackground: false, hasBorders: false, imageShow: true, imageUrl: 'https://source.unsplash.com/400x300/?donut', imageSize: 'full', imageHeight: 75, imageWidth: 75, imageShape: 'circle', imageShapeStretch: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', imageWidthUnitTablet: '%', imageWidthUnitMobile: '%',
			}, innerBlocks: [],
		}, {
			clientId: '23cadd15-2108-442d-a4aa-4ef41379d537', name: 'stackable/heading', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-heading stk-block-heading stk-block stk-0edd499" data-block-id="0edd499"><style>.stk-0edd499 .stk-block-heading__text{margin:0 !important}</style><h3 class="stk-block-heading__text">Title for This Block</h3></div>', attributes: {
				uniqueId: '0edd499', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, textRemoveTextMargins: true, hasP: false, show: true, showText: true, text: 'Title for This Block', textTag: 'h3', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		}, {
			clientId: '284b22b8-7df9-49d9-9df9-94c7bbf4c268', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-text stk-block-text stk-block stk-635f14c" data-block-id="635f14c"><p class="stk-block-text__text">Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.</p></div>', attributes: {
				uniqueId: '635f14c', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		}, {
			clientId: '21f49ee3-dd3c-4975-af61-91252abf3c70', name: 'stackable/button-group', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button-group stk-block-button-group stk-block stk-b37a0ec" data-block-id="b37a0ec"><div class="stk-row stk-inner-blocks stk-block-content stk-button-group"></div></div>', attributes: {
				uniqueId: 'b37a0ec', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%',
			}, innerBlocks: [ {
				clientId: '81b6fc58-8f44-41a0-bdce-f2f9b17d3cae', name: 'stackable/button', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button stk-block-button is-style-plain stk-block stk-11990c0" data-block-id="11990c0"><style>.stk-11990c0 .stk-button{background:transparent !important}</style><a class="stk-link stk-button" href=""><span class="stk-button__inner-text">Button</span></a></div>', attributes: {
					uniqueId: '11990c0', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, buttonBackgroundColor: 'transparent', linkHasLink: true, linkNewTab: false, linkHasTitle: true, showBackgroundShape: false, hasP: false, show: true, showText: true, text: 'Button', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em', className: 'is-style-plain',
				}, innerBlocks: [],
			} ],
		} ],
	}, {
		clientId: '2717f2b2-1cc1-4c07-bebe-3c0b1f813c6e', name: 'stackable/column', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-column stk-block-column stk-column stk-block stk-8d99f14" data-block-id="8d99f14"><div class="stk-block-content stk-inner-blocks stk-column-wrapper stk-block-column__content stk-container stk-8d99f14-container stk-hover-parent">\n\n\n\n\n\n</div></div>', attributes: {
			uniqueId: '8d99f14', hasBackground: false, hasBorders: false, hasContainer: true, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', containerBackgroundCustomSizeUnit: '%', containerBackgroundCustomSizeUnitTablet: '%', containerBackgroundCustomSizeUnitMobile: '%',
		}, innerBlocks: [ {
			clientId: 'c2b9970a-66cc-4dcb-ba65-cdf495182633', name: 'stackable/image', isValid: true, validationIssues: [], originalContent: "<div class=\"wp-block-stackable-image stk-block-image stk-block stk-744652d\" data-block-id=\"744652d\"><style>.stk-744652d .stk-img-wrapper{width:75px !important;height:75px !important}.stk-744652d .stk-img-wrapper img{mask-image:url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCI+PC9jaXJjbGU+PC9zdmc+') !important;-webkit-mask-image:url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCI+PC9jaXJjbGU+PC9zdmc+') !important}</style><figure class=\"stk-img-wrapper stk-img--shape\"><img class=\"stk-img\" src=\"https://source.unsplash.com/400x300/?coffee\" width=\"300\" height=\"300\"/></figure></div>", attributes: {
				uniqueId: '744652d', hasBackground: false, hasBorders: false, imageShow: true, imageUrl: 'https://source.unsplash.com/400x300/?coffee', imageSize: 'full', imageHeight: 75, imageWidth: 75, imageShape: 'circle', imageShapeStretch: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockLinkHasLink: true, blockLinkNewTab: false, blockLinkHasTitle: true, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', imageWidthUnitTablet: '%', imageWidthUnitMobile: '%',
			}, innerBlocks: [],
		}, {
			clientId: 'c5b720aa-1183-469b-baab-47b708dea1fe', name: 'stackable/heading', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-heading stk-block-heading stk-block stk-03761ef" data-block-id="03761ef"><style>.stk-03761ef .stk-block-heading__text{margin:0 !important}</style><h3 class="stk-block-heading__text">Title for This Block</h3></div>', attributes: {
				uniqueId: '03761ef', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, textRemoveTextMargins: true, hasP: false, show: true, showText: true, text: 'Title for This Block', textTag: 'h3', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		}, {
			clientId: 'c318c458-5f0f-49f7-9fdc-b91596a6dd23', name: 'stackable/text', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-text stk-block-text stk-block stk-0d46d83" data-block-id="0d46d83"><p class="stk-block-text__text">Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.</p></div>', attributes: {
				uniqueId: '0d46d83', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, hasP: false, show: true, showText: true, text: 'Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em',
			}, innerBlocks: [],
		}, {
			clientId: 'f82c39fa-f999-44e1-800f-79659343c644', name: 'stackable/button-group', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button-group stk-block-button-group stk-block stk-fe6e7e0" data-block-id="fe6e7e0"><div class="stk-row stk-inner-blocks stk-block-content stk-button-group"></div></div>', attributes: {
				uniqueId: 'fe6e7e0', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%',
			}, innerBlocks: [ {
				clientId: 'f4c69f01-d90c-499d-85c3-34f24cedf181', name: 'stackable/button', isValid: true, validationIssues: [], originalContent: '<div class="wp-block-stackable-button stk-block-button is-style-plain stk-block stk-b0a3903" data-block-id="b0a3903"><style>.stk-b0a3903 .stk-button{background:transparent !important}</style><a class="stk-link stk-button" href=""><span class="stk-button__inner-text">Button</span></a></div>', attributes: {
					uniqueId: 'b0a3903', hasBackground: false, hasBorders: false, effectAnimationOut: {}, effectAnimationIn: {}, customAttributes: [], hideDesktop: false, hideTablet: false, hideMobile: false, displayCondition: {}, buttonBackgroundColor: 'transparent', linkHasLink: true, linkNewTab: false, linkHasTitle: true, showBackgroundShape: false, hasP: false, show: true, showText: true, text: 'Button', blockBackgroundCustomSizeUnit: '%', blockBackgroundCustomSizeUnitTablet: '%', blockBackgroundCustomSizeUnitMobile: '%', lineHeightUnit: 'em', lineHeightUnitTablet: 'em', lineHeightUnitMobile: 'em', className: 'is-style-plain',
				}, innerBlocks: [],
			} ],
		} ],
	} ],
}
